 
name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: test snyk
      working-directory: /opt/snyk/
      run: pwd
