
name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: QIPDNS116
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: 935108ec-6fcc-41cd-b8f9-14b342aea9fc
